GFORMS-1302 ATL mini check your answers
hmrc/gform-frontend pull request #1278
Opened 2021-08-13 13:31 UTC by girishkamat

2021-08-16 11:20 UTC, josef-vlach requested changes
It is crashing when `defaultPage` is defined. It crashes when second cya should be displayed.

2021-08-16 11:20 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/gform/SectionRenderingService.scala
> +    val edit = request.getQueryString("edit").fold(false)(_.toBoolean)
`toBoolean` is not safe. Let's wrap it in `Try` os something.

2021-08-17 10:43 UTC, girishkamat commented
@josef-vlach I had to filter the invisible iterations from the render page model, to get it working (all changes in FormController). Does that look ok?

2021-08-17 11:42 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/gform/FormController.scala
> +                      formModelOptics.formModelVisibilityOptics.formModel.addToListBrackets.collectFirst {
Can't you use `def bracket(sectionNumber: SectionNumber): Bracket[A]` defined on `FormModel`?

2021-08-17 11:49 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/gform/FormController.scala
> +                        .fold[Option[Bracket.AddToListIteration[Visibility]]](_ => None)(_ => None)(a =>
You can use `withAddToListBracket` method on `Bracket`

2021-08-17 11:57 UTC, josef-vlach approved these changes

2021-08-17 11:57 UTC, merged