GFORMS-1596 - Make sort code one field in bank account details request
hmrc/gform-frontend pull request #1381
Opened 2021-12-13 09:03 UTC by DursunGundogan

2021-12-13 11:29 UTC, josef-vlach requested changes

2021-12-13 12:25 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/gform/DataRetrieveService.scala
> +                sortCode.stringRepresentation.replaceAll("[^0-9]", ""),
Hm, this will need more thinking, as this would cause problem with replaying formatted value back to the user.

2021-12-13 12:55 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/gform/DataRetrieveService.scala
> +                sortCode.stringRepresentation.replaceAll("[^0-9]", ""),
Actually replaying formatted data back to user is not a problem. So my initial suggestion still holds.

2021-12-16 12:06 UTC, DursunGundogan commented on app/uk/gov/hmrc/gform/gform/DataRetrieveService.scala
> +                sortCode.stringRepresentation.replaceAll("[^0-9]", ""),
Removed

2021-12-16 17:00 UTC, josef-vlach requested changes

2021-12-17 09:36 UTC, josef-vlach approved these changes

2021-12-17 12:22 UTC, merged