GFORMS: fix - Direction Back is not supported here
hmrc/gform-frontend pull request #1452
Opened 2022-03-11 09:53 UTC by lxol

2022-03-11 17:33 UTC, josef-vlach reviewed
This looks like it is on right path. but I wonder why simple don't change only `request.uri` for `.../submissions/new-form/...` on this line: https://github.com/hmrc/gform-frontend/blob/main/app/uk/gov/hmrc/gform/auth/models/RecoverAuthResult.scala#L53
?

2022-03-11 17:40 UTC, lxol commented
the problem there is that templateId is not available there. I had to wire it to the recovery method

2022-03-11 17:45 UTC, josef-vlach commented
Can you summon it like this:
```
val formTemplateWithRedirect: FormTemplateWithRedirects = request.attrs(FormTemplateKey)
```
?

2022-03-14 10:38 UTC, lxol commented
Do I need to handle `NoSuchElementException` if attribute is not in the request's header?
I can't see that it is handled anywhere in the code base.

2022-03-14 12:19 UTC, josef-vlach requested changes

2022-03-14 12:19 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/auth/models/RecoverAuthResult.scala
> +    case _: NoActiveSession if request.method == "POST" =>
Let's make this the same for all requests, no need to handle only POST differently.

2022-03-14 12:19 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/auth/models/RecoverAuthResult.scala
> +        s"${appConfig.`gform-frontend-base-url`}/submissions/new-form/${formTemplate._id.value}",
Let's not hardcode `/submissions/new-form/` here. 
We can use reverse route like `routes.NewFormController.dashboard(...)` instead.

2022-03-14 12:52 UTC, josef-vlach approved these changes

2022-03-14 12:54 UTC, merged