GFORMS-1589: Retrieve complete data set in free BARs check
hmrc/gform-frontend pull request #1473
Opened 2022-04-04 11:24 UTC by lxol

2022-04-04 13:32 UTC, DursunGundogan requested changes

2022-04-04 13:32 UTC, DursunGundogan commented on app/uk/gov/hmrc/gform/gform/DataRetrieveService.scala
> +                    DataRetrieveAttribute.SortCodeBankName                         -> validateResult.sortCodeBankName.getOrElse("asdfasf"),
```suggestion
                    DataRetrieveAttribute.SortCodeBankName                         -> validateResult.sortCodeBankName.getOrElse(""),
```

2022-04-05 07:40 UTC, lxol commented on app/uk/gov/hmrc/gform/gform/DataRetrieveService.scala
> +                    DataRetrieveAttribute.SortCodeBankName                         -> validateResult.sortCodeBankName.getOrElse("asdfasf"),
done

2022-04-05 08:10 UTC, DursunGundogan approved these changes

2022-04-05 08:12 UTC, merged