GFORMS-1966 - Change behaviour of back link
hmrc/gform-frontend pull request #1650
Opened 2022-11-08 17:51 UTC by DursunGundogan

2022-11-09 08:26 UTC, lxol commented on app/uk/gov/hmrc/gform/gform/FormController.scala
> +                  .summaryById(cache.formTemplateId, maybeAccessCode, sectionNumber.toCoordinates, None)
I think we should got to this route only for 
```
case FastFrorward.CYA(_, None)
```
If the second argument is `Some(sectionNumber)` it means that it is either ATL CYA pager or mini summary list CYA page

2022-11-09 08:27 UTC, lxol commented on app/uk/gov/hmrc/gform/gform/FormController.scala
> +                  .summaryById(cache.formTemplateId, maybeAccessCode, sectionNumber.toCoordinates, None)
I think we should go to this `sectionNumber` instead of the final CYA page

2022-11-09 08:39 UTC, lxol commented on app/uk/gov/hmrc/gform/gform/FormController.scala
> +                      backRoute(to, FastForward.Yes)
if we use FastForward.Yes here we won't be able to go back several times and then got forward step by step

2022-11-10 10:03 UTC, josef-vlach requested changes

2022-11-10 10:03 UTC, josef-vlach commented on public/javascripts/gformFormActionHandlers.js
> -          })
Can this really be removed? Be aware that this file apparently handles more stuff than back link click only.

2022-11-10 10:31 UTC, josef-vlach approved these changes

2022-11-10 10:59 UTC, merged