GFORMS-2356
hmrc/gform-frontend pull request #1955
Opened 2023-09-22 16:04 UTC by lxol

2023-09-22 16:20 UTC, josef-vlach requested changes

2023-09-22 16:20 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/controllers/ErrorHandler.scala
> +          logger.info(s"URL: ${requestHeader.uri}, Query Params: ${requestHeader.queryString}")
No need for a new `logger`, let use `smartUpstreamLogger.log` instead which will log message with ERROR level, which will help us to see it in Kibana

2023-09-22 16:29 UTC, josef-vlach approved these changes

2023-09-29 08:28 UTC, closed without merging

2023-09-29 08:29 UTC, lxol commented
it was a PR for review only