GFORMS-2372: Enable selectionCriteria on sicCode available in reveali…
hmrc/gform-frontend pull request #1962
Opened 2023-09-29 08:37 UTC by lxol

…ngChoice

2023-09-29 09:24 UTC, DursunGundogan approved these changes

2023-09-29 12:41 UTC, josef-vlach requested changes

2023-09-29 14:20 UTC, lxol commented on app/uk/gov/hmrc/gform/gform/SectionRenderingService.scala
>      val oFormComponent = aFormComponents.find(_.id.baseComponentId === formComponent.id.baseComponentId)
done

2023-10-02 08:13 UTC, josef-vlach approved these changes

2023-10-02 08:15 UTC, merged