GFORMS-2383: Improve error message displayed while clicking upload fi…
hmrc/gform-frontend pull request #1993
Opened 2023-11-15 17:56 UTC by lxol

…le button without selecting file

2023-11-15 18:42 UTC, josef-vlach requested changes
There is no consistency for js and non-js users when file is not selected.

js users see error: Select a file
non-js users see error: Select a file. It must be a PDF, JPG, XLSX, ODS, DOCX, ODT, PPTX, ODP.

Also for non-js users upload of empty file case is not properly detected anymore.

2023-11-15 18:42 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/upscan/UpscanController.scala
> +            val formComponent = formModel.fcLookup.get(formComponentId)
This is done on 200-201, it deserves some refactoring

2023-11-15 18:49 UTC, lxol commented
nonjs and js can't be consistently. We have different ACs for nonjs

2023-11-15 18:50 UTC, lxol commented
Empty file detection should stay the same. I will have a look tomorrow

2023-11-16 09:38 UTC, lxol commented
>Also for non-js users upload of empty file case is not properly detected anymore.
I think it has the same behavior for empty file. Looks like locally upscan returns a generic error that I changes according to ACs. I believe it will be the same in QA.

2023-11-16 10:09 UTC, josef-vlach approved these changes
Reusing is `error_action_redirect` is neat solution 👍

2023-11-16 10:15 UTC, merged