GFORMS-2906 - Add the ability to look up a rate from a csv
hmrc/gform-frontend pull request #2299
Opened 2024-10-25 13:06 UTC by cmanson

2024-10-25 16:37 UTC, josef-vlach requested changes

2024-10-25 16:37 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/gform/csv/CsvTaxRateAdapter.scala
> +case class TaxRate(regime: String, code: String, rate: String, startDate: LocalDate, endDate: LocalDate)
`rate` must be a number

2024-10-28 14:16 UTC, cmanson commented
Hi @josef-vlach, I've addressed all PR comments now I believe.

2024-10-28 17:18 UTC, josef-vlach requested changes

2024-10-28 17:18 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/gform/csv/CsvTaxRateAdapter.scala
> +      case Success(taxRateRequest: TaxRateRequest) =>
We should use `Try` only if there is no better alternative. In this case we can use `validate` [method](https://github.com/playframework/play-json/blob/main/play-json/shared/src/main/scala/play/api/libs/json/JsReadable.scala#L37)

```
request.json.validate[TaxRateRequest] match {
      case JsSuccess(taxRateRequest, _) =>
```

2024-10-28 17:18 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/gform/csv/CsvTaxRateAdapter.scala
> +        throw exception
Perhaps better alternative would be to do this:
```
case JsError(e) =>
  throw new Exception(
    s"An error occurred attempting to unmarshal request: ${request.json}. Error: ${Json.stringify(JsError.toJson(e))}"
  )
```

I think explicit logging is not needed here. We can rely on default error handler logging instead.

2024-10-29 11:34 UTC, merged